insert into comments (contents, user_id, post_id)
values
 ('accumsan tellus nisi eu orci mauris lacinia sapien', 14, 95),
 ('nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus', 5, 28),
 ('ipsum aliquam non mauris morbi non lectus', 4, 56),
 ('in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec', 48, 92),
 ('sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt', 26, 9),
 ('integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem', 22, 69),
 ('phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor id', 18, 35),
 ('eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti', 23, 15),
 ('vestibulum ante ipsum primis in faucibus orci', 20, 94),
 ('purus aliquet at feugiat non', 11, 15),
 ('tincidunt eu felis fusce posuere felis sed', 11, 9),
 ('et ultrices posuere cubilia curae nulla dapibus dolor vel est', 8, 89),
 ('justo eu massa donec dapibus duis at velit eu est congue elementum in', 46, 72),
 ('quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit', 41, 4),
 ('eget massa tempor convallis nulla neque libero convallis eget', 32, 74),
 ('nam nulla integer pede justo lacinia eget tincidunt eget tempus', 32, 53),
 ('nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante', 2, 85),
 ('nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat', 38, 64),
 ('tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at diam', 22, 70),
 ('habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate', 35, 33),
 ('adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget', 5, 46),
 ('integer a nibh in quis justo', 21, 64),
 ('libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet', 40, 24),
 ('sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie', 7, 37),
 ('ut erat curabitur gravida nisi at nibh in hac habitasse', 5, 23),
 ('purus aliquet at feugiat non pretium', 11, 83),
 ('turpis sed ante vivamus tortor duis mattis egestas metus aenean', 27, 65),
 ('montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes', 35, 5),
 ('in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie', 2, 55),
 ('vel sem sed sagittis nam congue risus semper porta volutpat quam pede', 46, 71),
 ('praesent id massa id nisl venenatis lacinia aenean sit amet justo', 37, 98),
 ('ac leo pellentesque ultrices mattis odio donec vitae nisi', 24, 41),
 ('quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh', 7, 38),
 ('dolor quis odio consequat varius integer ac leo pellentesque', 25, 35),
 ('lobortis sapien sapien non mi integer ac neque duis bibendum morbi non', 44, 18),
 ('enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac', 11, 3),
 ('vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum', 38, 82),
 ('porttitor id consequat in consequat ut nulla sed', 49, 69),
 ('at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna', 28, 8),
 ('ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium', 4, 71),
 ('in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris', 28, 16),
 ('aenean fermentum donec ut mauris eget', 5, 23),
 ('rutrum ac lobortis vel dapibus at diam nam tristique tortor', 45, 86),
 ('feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut', 36, 72),
 ('phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi', 43, 55),
 ('est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante', 3, 39),
 ('lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat', 47, 58),
 ('mi in porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse', 35, 28),
 ('ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum', 40, 99),
 ('ante ipsum primis in faucibus orci luctus et ultrices posuere', 28, 84),
 ('blandit nam nulla integer pede justo lacinia eget', 15, 33),
 ('ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non', 38, 58),
 ('pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus', 8, 26),
 ('sit amet sem fusce consequat nulla nisl nunc nisl duis', 10, 40),
 ('est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl', 34, 18),
 ('tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh', 8, 42),
 ('eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat', 38, 46),
 ('et ultrices posuere cubilia curae donec pharetra magna vestibulum', 47, 40),
 ('ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa', 21, 12),
 ('ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus', 15, 53),
 ('morbi non quam nec dui luctus rutrum nulla tellus in sagittis', 44, 13),
 ('pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis', 6, 19),
 ('cras mi pede malesuada in imperdiet et', 1, 7),
 ('sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede', 37, 56),
 ('elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis', 2, 15),
 ('justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus', 24, 86),
 ('rutrum at lorem integer tincidunt', 47, 41),
 ('proin at turpis a pede', 2, 50),
 ('sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis', 15, 42),
 ('sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse', 7, 75),
 ('a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis', 40, 91),
 ('lectus suspendisse potenti in eleifend', 4, 69),
 ('ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra', 13, 85),
 ('mattis pulvinar nulla pede ullamcorper augue a suscipit', 50, 96),
 ('donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac', 35, 90),
 ('turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a', 14, 11),
 ('mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet', 47, 64),
 ('ipsum primis in faucibus orci luctus et ultrices posuere', 43, 35),
 ('viverra eget congue eget semper rutrum', 12, 97),
 ('eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat', 22, 7),
 (' nunc donec quis orci eget orci vehic', 20, 42),
 ('ipsum integer a nibh in quis justo maecenas rhoncus', 5, 39),
 ('amet sem fusce consequat nulla nisl nunc nisl', 1, 24),
 ('as mi pede malesuada in imperdiet', 36, 97),
 ('eugiat non pretium quis lectus suspendisse potenti in eleifend', 5, 19),
 ('purus aliquet at', 44, 18);
 
 
 
 
 

