insert into users (username, bio, avatar, phone, email, password, status)
values
 ('Wally Itchingham', 'Chief Design Engineer', 'https://robohash.org/etutmaiores.png?size=50x50&set=set1', null, null, 'wygnlW5.', 'Mrs'),
 ('Jervis Bonhomme', 'Web Developer I', null, '274-479-4825', null, 'abixrB9}d|/p', 'Rev'),
 ('Gerhard Carren', 'Dental Hygienist', 'https://robohash.org/quidemdolorumautem.png?size=50x50&set=set1', '899-403-3270', null, 'fehisM5(?n', 'Mrs'),
 ('Eberto Magowan', 'Help Desk Operator', null, '785-315-0637', null, 'fgfcqY8~', 'Rev'),
 ('Yasmeen Beaton', 'Account Executive', null, null, null, 'metvkY3''fs(', 'Honorable'),
 ('Rosalynd Ivashintsov', 'Librarian', null, '683-291-7293', null, 'ybexjI5`ZnHa', 'Ms'),
 ('Ker Chong', 'Sales Representative', null, null, 'kchong6@smh.com.au', 'otnbaF1|>', 'Ms'),
 ('Noel Gascoyen', 'Legal Assistant', 'https://robohash.org/totamconsequunturnihil.png?size=50x50&set=set1', '242-735-7185', null, 'ybdqrS4|Jp"v', 'Mrs'),
 ('Talyah Olenchikov', 'Quality Control Specialist', 'https://robohash.org/rerummolestiaeet.png?size=50x50&set=set1', '821-251-6770', null, 'hldytD1<t', 'Ms'),
 ('Dennie Fortye', 'Information Systems Manager', 'https://robohash.org/dolorexvoluptatem.png?size=50x50&set=set1', null, null, 'ewbeeX3/', 'Ms'),
 ('Carolann Seed', 'Product Engineer', 'https://robohash.org/cupiditateducimustenetur.png?size=50x50&set=set1', '318-890-2596', null, 'vnpzuI4#t', 'Dr'),
 ('Zonda Mucci', 'Budget/Accounting Analyst III', 'https://robohash.org/nonveritatisqui.png?size=50x50&set=set1', '812-485-2007', null, 'zrpctK9!J(bkW', 'Rev'),
 ('Hermina Bruinemann', 'Nuclear Power Engineer', null, '769-365-3907', null, 'tzwxcP8(*BU_9', 'Mrs'),
 ('Annabell Olwen', 'Structural Engineer', null, null, null, 'rdpmeT1}.&', 'Ms'),
 ('Abdel Heys', 'Assistant Manager', 'https://robohash.org/suscipitistemollitia.png?size=50x50&set=set1', '440-244-8063', 'aheyse@cisco.com', 'ewibwF6!d!l', 'Mrs'),
 ('Jourdan McGrah', 'Technical Writer', null, '582-620-9137', null, 'ynigzX1|$9+Vh4S|', 'Dr'),
 ('Karissa Handling', 'Graphic Designer', 'https://robohash.org/etrepellendusut.png?size=50x50&set=set1', null, 'khandlingg@mayoclinic.com', 'ekcjpR9~!', 'Honorable'),
 ('Helena Moine', 'Electrical Engineer', null, null, 'hmoineh@indiegogo.com', 'kzixyR8=', 'Mrs'),
 ('Iain Trighton', 'Biostatistician IV', null, '246-639-4887', 'itrightoni@instagram.com', 'nuhmpF1!pzew+hQ', 'Ms'),
 ('Ertha Vittori', 'Sales Representative', null, '554-668-4611', 'evittorij@tuttocitta.it', 'orsvtT2`$M})ZF', 'Mr'),
 ('Danita Moxom', 'Nurse Practicioner', 'https://robohash.org/nostrumutet.png?size=50x50&set=set1', '487-401-8710', null, 'rfpsqA5(_WTQj', 'Honorable'),
 ('Clarance Van Vuuren', 'Internal Auditor', 'https://robohash.org/autvoluptatedistinctio.png?size=50x50&set=set1', '859-695-2282', null, 'stpmtX9}`p_{R&', 'Mr'),
 ('Myra Napton', 'Structural Analysis Engineer', null, '503-743-7617', null, 'hhfweJ8(+%IC6oH', 'Rev'),
 ('Myrvyn Jordeson', 'Director of Sales', 'https://robohash.org/cupiditatesequiut.png?size=50x50&set=set1', '440-692-0977', null, 'gqemcV3\SzV*', 'Rev'),
 ('Coriss Beacom', 'Electrical Engineer', null, '584-296-7644', null, 'bnefgD8&E9ir?Ga0', 'Mrs'),
 ('Brewer Dysert', 'Senior Quality Engineer', null, null, 'bdysertp@businesswire.com', 'lqhihW0=', 'Mrs'),
 ('Yale Codling', 'Programmer III', 'https://robohash.org/temporibusindolorem.png?size=50x50&set=set1', null, null, 'nfbqxQ2|/+}', 'Mrs'),
 ('Danit Hatwells', 'Design Engineer', null, null, null, 'mzkpkZ8+6+', 'Dr'),
 ('Reynolds Zorzoni', 'Compensation Analyst', 'https://robohash.org/solutacupiditateaccusamus.png?size=50x50&set=set1', '694-530-6038', null, 'ygpktW5)''iY5MFP,', 'Honorable'),
 ('Guillaume Kirby', 'Help Desk Operator', null, null, null, 'byqctL3>JT+.', 'Honorable'),
 ('Rycca Brumby', 'Financial Analyst', null, '551-715-4175', null, 'gcannM4!dH8e$5', 'Honorable'),
 ('Noemi Escudier', 'VP Sales', null, null, null, 'tiwafE4<', 'Mrs'),
 ('Shayla Tattershaw', 'Programmer II', null, '496-766-2670', null, 'ogmdsE2?B9', 'Dr'),
 ('Brandice Chucks', 'Environmental Tech', 'https://robohash.org/adliberonumquam.png?size=50x50&set=set1', '955-861-7120', null, 'cgtrxM1(i})v', 'Honorable'),
 ('Theodoric Garlette', 'Chief Design Engineer', null, '173-950-0042', null, 'ombteF4+>=gM', 'Mrs'),
 ('Zorah Pugsley', 'Marketing Manager', null, null, null, 'bbvlaS8?0R2J"', 'Ms'),
 ('Alameda Shambrooke', 'Information Systems Manager', 'https://robohash.org/nonmollitiain.png?size=50x50&set=set1', '544-557-1130', null, 'gtrwhX5_jEEC2k(', 'Mr'),
 ('Farrah Scrowson', 'Biostatistician IV', 'https://robohash.org/autemautet.png?size=50x50&set=set1', '902-466-3910', null, 'ilkwsT7`', 'Dr'),
 ('Lazarus Veasey', 'Web Designer I', null, null, null, 'inclsP2_#$Tw', 'Dr'),
 ('Robbie Wicher', 'Staff Scientist', null, '175-138-3332', null, 'bthfnW5}tR', 'Rev'),
 ('Justinian Gocher', 'Software Test Engineer III', 'https://robohash.org/rationererumaliquid.png?size=50x50&set=set1', null, null, 'ibuqpG2\/', 'Honorable'),
 ('Zsazsa Speek', 'Environmental Specialist', 'https://robohash.org/recusandaesequiut.png?size=50x50&set=set1', '703-211-8860', null, 'jsynqZ5&@', 'Dr'),
 ('Gregg Malser', 'Account Representative I', 'https://robohash.org/modicorruptisint.png?size=50x50&set=set1', null, null, 'ljvmwE9.u&orn~', 'Mrs'),
 ('Mikey Pryn', 'Payment Adjustment Coordinator', null, '224-699-8368', null, 'ckbhrE9#', 'Dr'),
 ('Rocky Ullyott', 'Director of Sales', null, '595-423-0526', 'rullyott18@hubpages.com', 'obdexA1\XuM*', 'Rev'),
 ('Lyell Skerritt', 'Associate Professor', 'https://robohash.org/sedprovidentqui.png?size=50x50&set=set1', null, null, 'jlxiqH4>0G`U~DX', 'Honorable'),
 ('Jervis Riddoch', 'Software Consultant', 'https://robohash.org/atquequisnam.png?size=50x50&set=set1', null, 'jriddoch1a@feedburner.com', 'ayduaV0~O8\', 'Dr'),
 ('Corney Gyurko', 'Civil Engineer', 'https://robohash.org/etautsit.png?size=50x50&set=set1', null, null, 'hlshrI0!wgRr&@v', 'Rev'),
 ('Wang De La Cote', 'VP Sales', null, '574-194-0263', null, 'hftfpI8*ywY', 'Ms'),
 ('Kara Blasi', 'Business Systems Development Analyst', null, '331-374-9135', null, 'vgxkpY3#C1', 'Mr');
     
